spring:
  application:
    name: Finance Tracker
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${POSTGRES_CONTAINER_NAME}:${DB_PORT}/${DB_NAME}
    password: ${DB_PASSWORD}
    username: ${DB_USER}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    open-in-view: false
  threads:
    virtual:
      enabled: true
  messages:
    basename: messages

springdoc:
  api-docs:
    enabled: true

telegram:
  url: https://api.telegram.org/bot7548438454:AAF4QQE9IQedG1F0PfWhaYT40z_iB76-2nY #https://1c00-37-110-210-1.ngrok-free.app
  token: 7548438454:AAF4QQE9IQedG1F0PfWhaYT40z_iB76-2nY
  name: Finance Tracker
  username: Finance_TrackBot

  # https://api.telegram.org/bot7548438454:AAF4QQE9IQedG1F0PfWhaYT40z_iB76-2nY/
  # https://api.telegram.org/bot7548438454:AAF4QQE9IQedG1F0PfWhaYT40z_iB76-2nY/deleteWebhook
  # https://api.telegram.org/bot7548438454:AAF4QQE9IQedG1F0PfWhaYT40z_iB76-2nY/setWebhook?url=https://1c00-37-110-210-1.ngrok-free.app/api/update

server:
  port: 80


