spring:
  application:
    name: Finance Tracker
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/finance-tracker-db
    password: password
    username: postgres
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true

    open-in-view: false
  threads:
    virtual:
      enabled: true
  messages:
    basename: messages

springdoc:
  api-docs:
    enabled: true

telegram:
  url: https://api.telegram.org/bot7548438454:AAF4QQE9IQedG1F0PfWhaYT40z_iB76-2nY #https://a90f-37-110-210-1.ngrok-free.app
  token: 7548438454:AAF4QQE9IQedG1F0PfWhaYT40z_iB76-2nY
  name: Finance Tracker
  username: Finance_TrackBot

  # https://api.telegram.org/bot7548438454:AAF4QQE9IQedG1F0PfWhaYT40z_iB76-2nY/
  # https://api.telegram.org/bot7548438454:AAF4QQE9IQedG1F0PfWhaYT40z_iB76-2nY/deleteWebhook
  # https://api.telegram.org/bot7548438454:AAF4QQE9IQedG1F0PfWhaYT40z_iB76-2nY/setWebhook?url=https://a90f-37-110-210-1.ngrok-free.app/api/update

token:
  expiration:
    access: 86400000    # 24 hours
    refresh: 604800000  # 7 days
  secret-key: vpwGiG8Hh659YkRNBnBZXW1a6pRWSfLBKyd4f4MigA8

cors:
  allowedHeaders: [ "*" ]
  allowedOrigins: [ "*" ]
  allowedMethods: [ "*" ]
  allowCredentials: true
  urlPattern: "/**"

server:
  port: 8080

project:
  log:
    mode: true
  host: localhost



